# Generated by Django 5.0.6 on 2024-10-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_person_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
